---
#
- name: install sonarqube
  unarchive:
    src: "{{ sonarqube_url }}"
    dest: "{{ sonarqube_base }}"
    owner: "{{ sonarqube_user }}"
    copy: no
    creates: "{{ sonarqube_home }}/bin/sonar"
  become: yes
