---
#
- name: install sonarqube
  unarchive:
    src: "{{ sonarqube_download_url }}"
    dest: "{{ sonarqube_home }}"
    copy: no
    creates: "{{ sonarqube_home }}/sonar/COPYING"

- name: configure sonarqube database connection
  lineinfile:
    dest: "{{ sonarqube_home }}/conf/sonar.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: restart sonar
  with_items:
    - regexp: "^sonar.jdbc.username"
      line: "sonar.jdbc.username={{ sonar_mysql_username }}"
    - regexp: "^sonar.jdbc.password"
      line: "sonar.jdbc.password={{ sonar_mysql_password }}"
    - regexp: "^sonar.jdbc.url"
      line: "sonar.jdbc.url=jdbc:mysql://{{ sonar_mysql_host }}:{{ sonar_mysql_port }}/{{ sonar_mysql_database }}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance"
