---
- name: install mysql python module
  yum: name=python-mysqldb
  when: ansible_os_family == "RedHat"

- name: install mysql python module
  apt: name=MySQL-python
  when: ansible_os_family == "RedHat"

- name: create a mylsql database
  mysql_db:
    name: "{{ sonarqube_mysql_database }}"
    state: present

- name: create sonar database user
  mysql_user:
    name: "{{ sonarqube_mysql_username }}"
    host: "{{ item }}"
    priv: "{{ sonarqube_mysql_database }}.*:ALL"
    password: "{{ sonarqube_mysql_password }}"
  with_items: sonarqube_mysql_allowed_hosts
