---
- name: install mysql python module
  pip: name=MySQL-python

- name: create a mylsql database
  mysql_db:
    name: "{{ sonarqube_mysql_database }}"
    state: present

- name: create sonar database user
  mysql_user:
    name: "{{ sonarqube_mysql_username }}"
    host: "{{ item }}"
    priv: "{{ sonarqube_mysql_database }}.*:ALL"
    password: "{{ sonarqube_mysql_password }}"
  with_items: sonarqube_mysql_allowed_hosts
